apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubectl-agent
  namespace: challenge2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubectl-deploy
rules:
  - apiGroups: [""]
    resources: ["pods", "replicasets", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubectl-agent
subjects:
  - kind: ServiceAccount
    name: kubectl-agent
    namespace: challenge2
roleRef:
  kind: ClusterRole
  name: kubectl-deploy
  apiGroup: rbac.authorization.k8s.io